### ISSUE TITLE
Devtool in browser Arc is not visible

### ISSUE THREAD

**Issue by KoenWouters** [beyondcode/devtoolsfortailwind-community#22]
I want to use the browser [Arc](https://arc.net/) as my browser. This browser is chromium based but i don't see the devtools in my inspector. Is it possible to fix this?

**Comment by martylouis** [comment]
Not sure if you checked here, but I can confirm that it's working for me in Arc.

<img width="830" alt="Arc--0414115655" src="https://user-images.githubusercontent.com/169188/232108840-a73f2149-4002-49df-8eb1-dbeae61bc649.png">

**Comment by KoenWouters** [comment]
Yes i checked here multiple times and checked the difference with my chrome and didn't see it. Just checked it again and it popped up now 😃 . Sorry for the issue, i will close it :)
